name: 🧪 BDD Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bdd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - run: npm ci

      - name: 🧪 Run BDD tests
        run: npm run bdd -- --format html:reports/bdd/index.html
      
      - name: 📤 Upload BDD artifact
        uses: actions/upload-artifact@v4
        with:
          name: bdd-reports
          path: reports/bdd/index.html
