name: Coverage Report
on: [push]
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: '18' }
      - run: npm install
      - name: Run tests with coverage
        run: npm test
      - name: Upload coverage report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage/lcov-report
          publish_branch: gh-pages
          publish_dir: coverage/lcov-report
          destination_dir: coverage
